### ISSUE TITLE
Clarify license information

### ISSUE THREAD

**Issue by avh4** [gdisf/teaching-materials#122]
http://www.teaching-materials.org/ says that the content here is "CC-licensed", but doesn't specify which one (https://creativecommons.org/licenses/#licenses).  It'd be great if the top-level README file made the situation clear (or a LICENSE file in the top-level folder).

**Comment by brendajin** [comment]
Here is the license we use per our new reveal slides:

https://creativecommons.org/licenses/by-nc/2.0/

Instead of copying the license to our root directory, please include a link on the main `README.md` and also link our reveal slide theme to that page

Here's what the bottom-right hand side of a correctly themed slide looks like:
![screen shot 2016-07-11 at 7 26 40 pm](https://cloud.githubusercontent.com/assets/2753545/16753281/72a4b19c-479d-11e6-938d-287b7608ce22.png)

**Comment by brendajin** [comment]
>

**Comment by brendajin** [comment]
This is being taken care of by converting our slides to `reveal.js`, and our template has the appropriate CC license link and details.
