### ISSUE TITLE
[ajax] Add Python 3 instructions

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#151]
Add python or Firefox installation prerequisite
Add instructions for Python 3 server

**Comment by verythorough** [comment]
I've just made a pull request fixing a similar issue in [APIs].  In APIs, the local server setup instructions are on their own page (apis/testinglocally.html), separate from the exercise instructions.  Since the new instructions are a bit long, a separate page might be better here, too.

Since students might need to run a local server for a number of workshops, I wonder if it makes sense to create a folder like teaching-materials/resources, and use it for general purpose instructions like this.  I'm sure there are other topics that would fall into this category as well.

For prerequisites, Readme docs for workshops requiring a local server setup could link the resources/testinglocally.html file in the Tech Requirements section.

**Comment by pamelafox** [comment]
Yeah, we could move it into a common folder, that'd work well.
