### ISSUE TITLE
[admin] Update example/ reveal.js slide template for teachers reference

### ISSUE THREAD

**Issue by trucnguyen** [gdisf/teaching-materials#260]
Branded GDI SF reveal js template, should show how to do:
Styling with code blocks, markdown, etc
Folder structure for exercises and solutions should be like
Using class="fragment" to slowly introduce concepts on a slide
Speaker notes?

**Comment by verythorough** [comment]
This sounds like a great idea!  I wonder if we should avoid sub-sections, though, as it's easy to miss whole blocks of content if you don't notice the indicator for vertical slides.

**Comment by brendajin** [comment]
We can skip the subsections for now since the national template advises against them. Is there anything else we should include to make curriculum updates/development faster/easier?

**Comment by verythorough** [comment]
The current list looks good.  I'll see if I can think of anything else.

One thing I find myself wondering about as a teacher is the [speaker notes](https://github.com/hakimel/reveal.js/#speaker-notes) capability.  I'm guessing this is another thing national might warn against, since most won't even know they're there.  On the other hand, sometimes slide content is pretty cryptic, and having notes to explain the author's intentions could be helpful.

**Comment by brendajin** [comment]
Cryptic content should definitely be avoided, because students will need this material after workshops. If we see any cryptic material, we need to flag it as needing more accompanying text/visuals.

**Comment by brendajin** [comment]
Tasks for this issue:

- [ ] Update `/example` directory per instructions above
- [ ] Make sure you load the example slides in browser and check your work before submitting

**Comment by caraya** [comment]
I'll start working on this issue
